title: Chris Flores
logo: /assets/img/website profile smaller.jpg
show_downloads: false
description: You can reach me at <em><strong>floresc@stanford.edu.</strong></em>.
google_analytics:
theme: jekyll-theme-minimal
