title: Chris Flores
logo: /assets/img/website profile smaller.jpg
show_downloads: false
description: <br> You can reach me at <strong>floresc@stanford.edu.</strong>
google_analytics:
theme: jekyll-theme-minimal
